insert into cars (make, model, color, year, price) values ('Saturn', 'VUE', 'Yellow', 2004, 22408);
insert into cars (make, model, color, year, price) values ('Volvo', 'C30', 'Green', 2011, 15618);
insert into cars (make, model, color, year, price) values ('Hyundai', 'XG350', 'Violet', 2004, 26829);
insert into cars (make, model, color, year, price) values ('Toyota', 'Camry Solara', 'Violet', 2007, 95856);
insert into cars (make, model, color, year, price) values ('Ford', 'F250', 'Crimson', 1998, 1638);
insert into cars (make, model, color, year, price) values ('Audi', '5000S', 'Orange', 1984, 67168);
insert into cars (make, model, color, year, price) values ('Jeep', 'Patriot', 'Violet', 2012, 40333);
insert into cars (make, model, color, year, price) values ('Cadillac', 'Escalade', 'Turquoise', 2010, 89848);
insert into cars (make, model, color, year, price) values ('BMW', 'X6', 'Maroon', 2010, 95169);
insert into cars (make, model, color, year, price) values ('Mercury', 'Grand Marquis', 'Maroon', 2008, 52632);
insert into cars (make, model, color, year, price) values ('Audi', 'V8', 'Red', 1992, 95940);
insert into cars (make, model, color, year, price) values ('Tesla', 'Roadster', 'Violet', 2012, 85425);
insert into cars (make, model, color, year, price) values ('Mercedes-Benz', 'C-Class', null, 1998, 59297);
insert into cars (make, model, color, year, price) values ('Plymouth', 'Colt Vista', 'Puce', 1994, 78124);
insert into cars (make, model, color, year, price) values ('Acura', 'TSX', null, 2011, 41092);
insert into cars (make, model, color, year, price) values ('Kia', 'Forte', 'Blue', 2010, 71514);
insert into cars (make, model, color, year, price) values ('Panoz', 'Esperante', null, 2007, 67409);
insert into cars (make, model, color, year, price) values ('Chevrolet', 'Silverado 1500', 'Puce', 2012, 62033);
insert into cars (make, model, color, year, price) values ('Subaru', 'Outback', 'Turquoise', 2009, 97827);
insert into cars (make, model, color, year, price) values ('Subaru', 'SVX', 'Aquamarine', 1993, 14128);
insert into cars (make, model, color, year, price) values ('Volvo', '850', 'Turquoise', 1995, 34992);
insert into cars (make, model, color, year, price) values ('Mercury', 'Cougar', 'Puce', 1988, 2997);
insert into cars (make, model, color, year, price) values ('Chevrolet', 'Monte Carlo', 'Turquoise', 1996, 62308);
insert into cars (make, model, color, year, price) values ('Pontiac', 'Bonneville', 'Orange', 1991, 94076);
insert into cars (make, model, color, year, price) values ('Ford', 'Fusion', 'Red', 2006, 89698);
insert into cars (make, model, color, year, price) values ('GMC', '3500', 'Red', 1998, 40258);
insert into cars (make, model, color, year, price) values ('Volkswagen', 'Golf', 'Indigo', 1998, 30819);
insert into cars (make, model, color, year, price) values ('Lexus', 'SC', 'Crimson', 2003, 45669);
insert into cars (make, model, color, year, price) values ('Mercury', 'Sable', 'Indigo', 1999, 73840);
insert into cars (make, model, color, year, price) values ('Volvo', 'S40', 'Pink', 2005, 57147);
insert into cars (make, model, color, year, price) values ('Ford', 'Focus', 'Crimson', 2002, 45851);
insert into cars (make, model, color, year, price) values ('Toyota', 'Solara', 'Indigo', 2004, 29817);
insert into cars (make, model, color, year, price) values ('GMC', 'Envoy', 'Blue', 2005, 74711);
insert into cars (make, model, color, year, price) values ('Dodge', 'Viper', 'Green', 2005, 33875);
insert into cars (make, model, color, year, price) values ('Mercury', 'Cougar', 'Crimson', 1984, 13660);
insert into cars (make, model, color, year, price) values ('Land Rover', 'Freelander', 'Turquoise', 2004, 90783);
insert into cars (make, model, color, year, price) values ('Infiniti', 'FX', 'Fuscia', 2003, 38088);
insert into cars (make, model, color, year, price) values ('Mercury', 'Tracer', 'Indigo', 1996, 54304);
insert into cars (make, model, color, year, price) values ('Ford', 'Probe', 'Orange', 1992, 54203);
insert into cars (make, model, color, year, price) values ('Nissan', 'Xterra', 'Teal', 2005, 82388);
insert into cars (make, model, color, year, price) values ('Mazda', 'Mazda6', 'Fuscia', 2013, 85112);
insert into cars (make, model, color, year, price) values ('Dodge', 'Daytona', 'Green', 1993, 18199);
insert into cars (make, model, color, year, price) values ('Jaguar', 'XJ', 'Fuscia', 2010, 78405);
insert into cars (make, model, color, year, price) values ('BMW', '750', 'Orange', 2006, 57629);
insert into cars (make, model, color, year, price) values ('Buick', 'Riviera', 'Aquamarine', 1986, 36976);
insert into cars (make, model, color, year, price) values ('Ford', 'EXP', 'Turquoise', 1985, 31144);
insert into cars (make, model, color, year, price) values ('Lexus', 'ES', 'Orange', 1989, 83231);
insert into cars (make, model, color, year, price) values ('GMC', 'Suburban 1500', 'Puce', 1997, 96533);
insert into cars (make, model, color, year, price) values ('Maybach', '62', 'Red', 2010, 52324);
insert into cars (make, model, color, year, price) values ('BMW', '5 Series', 'Pink', 2001, 8041);
